name: Flutter CI

on:
  push:
    branches:
      - 'master'

jobs:
#   prepare:
#     runs-on: ubuntu-latest
#     if: "! contains(github.event.head_commit.message, '[ci skip]')"
#     steps:
#       - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: macOS-latest
#    runs-on: ubuntu-latest
#     needs: prepare

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

#      - name: Setup flutter
#        uses: subosito/flutter-action@v2.7.1
#        with:
#          flutter-version: '3.3.1'
#     Flutterセットアップ高速化
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable

#       - name: Set up test tools
#         run: |
#           flutter pub get
#           flutter pub global activate dart_dot_reporter
#           flutter pub global activate junitreport
#           pip install junit2html

      - name: Test
        run: |
          export PATH=$PATH:${FLUTTER_HOME}/bin/cache/dart-sdk/bin
          export PATH=$PATH:${FLUTTER_HOME}/.pub-cache/bin
          pwd
          cd my_app
          flutter test --machine > test_report.log
          cat test_report.log
          echo 'Tests done.'

#      - name: Test Report
#       uses: phoenix-actions/test-reporting@v8
#        uses: dorny/test-reporter@v1.5.0
#        if: always()
#        with:
#          name: 'flutter test'
#          path: 'my_app/test_report.log'
#          reporter: 'flutter-json'
#          fail-on-error: 'false'

#       - name: Slack notification
#         if: always()
#         uses: homoluctus/slatify@master
#         with:
#           type: ${{ job.status }}
#           job_name: '*Build and DebugCheck*'
#           channel: '#general'
#           commit: true
#           token: ${{ secrets.GITHUB_TOKEN }}
#           url: ${{ secrets.SLACK_WEBHOOK_URL }}
